from __future__ import annotations


class vtkFLUENTCFFReader:
    """Python binding for the local Fluent CFF VTK reader."""

    def __init__(self) -> None: ...

    def SetFileName(self, file_name: str) -> None: ...
    def GetFileName(self) -> str: ...

    def SetDataFileName(self, data_file_name: str) -> None: ...
    def GetDataFileName(self) -> str: ...

    def SetRenameArrays(self, rename_arrays: int) -> None: ...
    def GetRenameArrays(self) -> int: ...

    def SetExcludedFieldArrayNames(self, names: list[str]) -> None: ...
    def ClearExcludedFieldArrayNames(self) -> None: ...
    def GetExcludedFieldArrayNames(self) -> list[str]: ...

    def Update(self) -> None: ...

    def GetNumberOfFaceZones(self) -> int: ...
    def GetFaceZoneName(self, index: int) -> str: ...
    def GetFaceZoneIdByName(self, name: str) -> int: ...
    def GetFaceZoneType(self, zone_id: int) -> int: ...
    def GetCellZoneType(self, zone_id: int) -> int: ...
